// Generated by `pnpm sprites:build`. Do not edit by hand - change the source in
// `sources/` or its row in `scripts/build-sprite-assets.mjs`, and rebuild.
import type { BackdropArt, SpriteArt } from "./types.ts";

export const SPRITE_ARTS: readonly SpriteArt[] = [
  {
    id: "sprite-asteroids",
    bytes: 54136,
    url: new URL("../sprites/sprite-asteroids.webp", import.meta.url).href,
    width: 1024,
    height: 256,
    frameWidth: 256,
    frameHeight: 256,
    frames: 3
  },
  {
    id: "sprite-enemy-fighter",
    bytes: 21660,
    url: new URL("../sprites/sprite-enemy-fighter.webp", import.meta.url).href,
    width: 256,
    height: 256,
    frameWidth: 256,
    frameHeight: 256,
    frames: 1
  },
  {
    id: "sprite-enemy-heavy",
    bytes: 21166,
    url: new URL("../sprites/sprite-enemy-heavy.webp", import.meta.url).href,
    width: 256,
    height: 256,
    frameWidth: 256,
    frameHeight: 256,
    frames: 1
  },
  {
    id: "sprite-enemy-orb",
    bytes: 24570,
    url: new URL("../sprites/sprite-enemy-orb.webp", import.meta.url).href,
    width: 256,
    height: 256,
    frameWidth: 256,
    frameHeight: 256,
    frames: 1
  },
  {
    id: "sprite-player",
    bytes: 20538,
    url: new URL("../sprites/sprite-player.webp", import.meta.url).href,
    width: 256,
    height: 256,
    frameWidth: 256,
    frameHeight: 256,
    frames: 1
  }
];

export const BACKDROP_ARTS: readonly BackdropArt[] = [
  {
    id: "deep-nebula",
    bytes: 217990,
    url: new URL("../backdrops/deep-nebula.webp", import.meta.url).href,
    width: 1672,
    height: 941
  }
];
