// Generated by `pnpm fx:bake`. Do not edit by hand - edit the sources in
// `effects/` and re-bake, or the next bake overwrites you.
import type { FxEffect } from "./types.ts";

export const FX_EFFECTS: readonly FxEffect[] = [
  {
    id: "debris-burst",
    title: "Разрушение",
    category: "destruction",
    hint: "Кольцо ударной волны и разлёт осколков — под уничтожение врага или куска корпуса.",
    oriented: false,
    loop: false,
    bytes: 326640,
    url: new URL("../atlases/debris-burst.png", import.meta.url).href,
    meta: {
      frameWidth: 128,
      frameHeight: 128,
      cols: 4,
      rows: 4,
      frames: 16,
      fps: 26.67,
      duration: 0.6
    }
  },
  {
    id: "explosion",
    title: "Взрыв",
    category: "explosion",
    hint: "Вспышка, искры, ударная волна, пламя и дым. Круговой — поворачивать не нужно.",
    oriented: false,
    loop: false,
    bytes: 427026,
    url: new URL("../atlases/explosion.png", import.meta.url).href,
    meta: {
      frameWidth: 112,
      frameHeight: 112,
      cols: 6,
      rows: 4,
      frames: 24,
      fps: 43.64,
      duration: 0.55
    }
  },
  {
    id: "muzzle-flash",
    title: "Дульная вспышка",
    category: "muzzle",
    hint: "Короткий выброс у дула, около 0.14 с. Направленный: в атласе смотрит вверх, как выхлоп.",
    oriented: true,
    loop: false,
    bytes: 75627,
    url: new URL("../atlases/muzzle-flash.png", import.meta.url).href,
    meta: {
      frameWidth: 96,
      frameHeight: 96,
      cols: 4,
      rows: 3,
      frames: 12,
      fps: 50,
      duration: 0.24
    }
  },
  {
    id: "muzzle-flash-mg",
    title: "Дульная вспышка (пулемёт)",
    category: "muzzle",
    hint: "Тёплая короткая вспышка носового пулемёта, ~0.09 с. Направленная: в атласе смотрит вверх.",
    oriented: true,
    loop: false,
    bytes: 10738,
    url: new URL("../atlases/muzzle-flash-mg.png", import.meta.url).href,
    meta: {
      frameWidth: 64,
      frameHeight: 64,
      cols: 4,
      rows: 2,
      frames: 8,
      fps: 50,
      duration: 0.16
    }
  },
  {
    id: "plasma-exhaust",
    title: "Плазменный выхлоп",
    category: "exhaust",
    hint: "Луп сопла. В атласе струя смотрит вверх, дисплей поворачивает её по курсу корабля и растягивает по передней скорости.",
    oriented: true,
    loop: true,
    bytes: 157622,
    url: new URL("../atlases/plasma-exhaust.png", import.meta.url).href,
    meta: {
      frameWidth: 48,
      frameHeight: 128,
      cols: 4,
      rows: 4,
      frames: 16,
      fps: 32,
      duration: 0.5
    }
  },
  {
    id: "shield-band",
    title: "Барьер щита",
    category: "shield",
    hint: "Луп ленты энергии. Дисплей гнёт её по дуге поднятого сектора, поэтому в атласе она прямая и горизонтальная, а яркость берёт от заряда.",
    oriented: false,
    loop: true,
    bytes: 246018,
    url: new URL("../atlases/shield-band.png", import.meta.url).href,
    meta: {
      frameWidth: 256,
      frameHeight: 36,
      cols: 4,
      rows: 4,
      frames: 16,
      fps: 32,
      duration: 0.5
    }
  },
  {
    id: "shield-impact",
    title: "Попадание в щит",
    category: "shield",
    hint: "Вспышка контакта, рябь и брызги искр, ~0.22 с. Направленный: в атласе смотрит вверх, точка контакта на нижней кромке.",
    oriented: true,
    loop: false,
    bytes: 30512,
    url: new URL("../atlases/shield-impact.png", import.meta.url).href,
    meta: {
      frameWidth: 64,
      frameHeight: 64,
      cols: 4,
      rows: 3,
      frames: 12,
      fps: 54.55,
      duration: 0.22
    }
  }
];
