/**
 * Generated by `pnpm balance:promote`; do not edit by hand.
 *
 * The same number as `presets/production.revision`, which the release script
 * reads as text. It is mirrored here because a bundler cannot read a plain file
 * the way a shell can, and a device has to know which promoted numbers it is
 * carrying.
 */
export const SEED_REVISION = 4;
