import { useState, type ReactElement } from "react";
import {
  FX_CATEGORY_LABELS,
  FX_EFFECTS,
  getPopulatedFxCategories,
  type FxCategory
} from "@spaceship-defender/fx-assets";

import { EffectPreview } from "./EffectPreview.js";
import { spriteFrameStyle } from "./playback.js";

/** The grid's own thumbnails; a card is a still, the preview is what moves. */
const THUMBNAIL_SCALE = 0.75;
const ALL = "all";

/**
 * The catalogue of baked effects.
 *
 * Read-only on purpose: this page says what exists and what it is made of, so
 * an effect can be picked before anything is wired to a ship. Attaching one to
 * a hardpoint would put a choice in the balance file, and that is a separate
 * change with a schema version behind it.
 *
 * Everything comes from `@spaceship-defender/fx-assets`, which is generated by
 * `pnpm fx:bake` at build time - so the page needs no request, no password and
 * no server route.
 */
export function EffectsScreen(): ReactElement {
  const categories = getPopulatedFxCategories();
  const [filter, setFilter] = useState<FxCategory | typeof ALL>(ALL);
  const [selectedId, setSelectedId] = useState(FX_EFFECTS[0]?.id ?? "");

  // Annotated because an array literal widens its elements: `[ALL, ...]` alone
  // infers string[], and the chips stop narrowing against the filter.
  const chips: readonly (FxCategory | typeof ALL)[] = [ALL, ...categories];
  const shown = filter === ALL ? FX_EFFECTS : FX_EFFECTS.filter((fx) => fx.category === filter);
  // The selection survives a filter that hides it, so switching back does not
  // silently move the operator to another effect.
  const selected = FX_EFFECTS.find((fx) => fx.id === selectedId) ?? shown[0];

  return (
    <section className="screen">
      <header className="screen__header">
        <h2>Эффекты</h2>
        <p className="screen__hint">
          Запечённые спрайт-атласы из <code>packages/fx-assets</code>. Исходники живут в{" "}
          <code>effects/*.json</code>, атласы пересобирает <code>pnpm fx:bake</code>. Выхлоп уже
          стоит на корабле; остальные пока только в каталоге.
        </p>
      </header>

      <nav aria-label="Категории эффектов" className="fx-filter">
        {chips.map((candidate) => (
          <button
            className={`fx-filter__chip${candidate === filter ? " fx-filter__chip--active" : ""}`}
            data-testid={`fx-filter-${candidate}`}
            key={candidate}
            onClick={() => {
              setFilter(candidate);
            }}
            type="button"
          >
            {candidate === ALL ? "Все" : FX_CATEGORY_LABELS[candidate]}
          </button>
        ))}
      </nav>

      <div className="fx-layout">
        <ul className="fx-grid" data-testid="fx-grid">
          {shown.map((effect) => (
            <li key={effect.id}>
              <button
                className={`fx-card${effect.id === selected?.id ? " fx-card--active" : ""}`}
                data-testid={`fx-card-${effect.id}`}
                onClick={() => {
                  setSelectedId(effect.id);
                }}
                type="button"
              >
                <span
                  className="fx-card__thumb"
                  style={spriteFrameStyle(
                    effect,
                    Math.floor(effect.meta.frames / 3),
                    THUMBNAIL_SCALE
                  )}
                />
                <span className="fx-card__title">{effect.title}</span>
                <span className="fx-card__facts">
                  {FX_CATEGORY_LABELS[effect.category]} · {effect.meta.frames} кадров ·{" "}
                  {effect.meta.fps} fps
                </span>
              </button>
            </li>
          ))}
        </ul>
        {selected === undefined ? (
          <p className="screen__hint">
            Каталог пуст — атласы ещё не запечены. Запустите <code>pnpm fx:bake</code>.
          </p>
        ) : (
          <EffectPreview effect={selected} />
        )}
      </div>
    </section>
  );
}
